/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import javafx.application.Application
import org.example.visuales.HolaJavaFX

fun main() {
    Application.launch(HolaJavaFX::class.java)
}